# Generated by Django 5.1.7 on 2026-02-19 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='option',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('author_type', 'human'), ('llm_model__isnull', True)), models.Q(('author_type', 'ai'), ('llm_model__isnull', False)), _connector='OR'), name='option_author_type_llm_model_match'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('choice_count__in', [2, 4])), name='question_choice_count_2_or_4'),
        ),
    ]
