# Generated by Django 5.1.7 on 2026-02-19 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=20)),
                ('choice_count', models.PositiveSmallIntegerField()),
                ('num_questions_requested', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField()),
                ('shuffle_map_json', models.JSONField(default=dict)),
                ('phase1_selected_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('phase1_is_correct', models.BooleanField(blank=True, null=True)),
                ('phase1_answered_at', models.DateTimeField(blank=True, null=True)),
                ('phase1_time_ms', models.IntegerField(blank=True, null=True)),
                ('phase2_assignment_json', models.JSONField(blank=True, null=True)),
                ('phase2_score', models.IntegerField(blank=True, null=True)),
                ('phase2_is_perfect', models.BooleanField(blank=True, null=True)),
                ('phase2_answered_at', models.DateTimeField(blank=True, null=True)),
                ('phase2_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_questions', to='content.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='quiz.quizsession')),
            ],
            options={
                'ordering': ['order_index'],
                'constraints': [models.UniqueConstraint(fields=('session', 'order_index'), name='unique_order_per_session'), models.UniqueConstraint(fields=('session', 'question'), name='unique_question_per_session')],
            },
        ),
        migrations.CreateModel(
            name='UserSeenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('solved', 'Solved')], default='reserved', max_length=20)),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_by_users', to='content.question')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seen_questions', to='quiz.quizsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='unique_seen_question_per_user')],
            },
        ),
    ]
